name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test with ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "^1.25.1"
      - name: Format check
        run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Type check
        run: ./scripts/type-check.mjs
      - name: Install
        run: ./scripts/install.sh
      - name: Test
        run: ./scripts/test.sh
